language: ruby
os: linux

_ruby_supported_versions:
  - &ruby_2_3 2.3.8
  - &ruby_2_4 2.4.9
  - &ruby_2_5 2.5.7
  - &ruby_2_6 2.6.5

  - &rails_5_2 RAILS_VERSION=5.2
  - &rails_6_0 RAILS_VERSION=6.0
  - &rails_master RAILS_VERSION=master

cache:
  directories:
    - vendor/bundle

before_install:
  - "travis_retry gem update --system 2.7.9"
  - "travis_retry gem install bundler -v '1.17.3'"
install: bundle install --path=vendor/bundle --retry=3 --jobs=3

script:
  - bundle exec rake ci
after_success:
  - codeclimate-test-reporter

env:
  global:
    - BUNDLER_VERSION=1.17.3
  jobs:
    - *rails_5_2
    - *rails_6_0
    - *rails_master

rvm:
  - *ruby_2_5
  - *ruby_2_6

-jobs:
  include:
    - { rvm: *ruby_2_3, env: *rails_5_2 }
    - { rvm: *ruby_2_4, env: *rails_5_2 }

branches:
  only: 0-10-stable
